workflow:
    rules:
        # Only trigger for merge requests to factory. As the pipeline is currently only setup for factory.
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event' &&
              $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'factory'
        # Or trigger manually in the web client under 'Build > Pipelines'.
        - if: $CI_PIPELINE_SOURCE == 'web'

image: registry.opensuse.org/opensuse/tumbleweed:latest

stages:
    - build
    - rpmbuild
    - test

# Based on https://github.com/fedora-selinux/selinux-policy/blob/6063934d9591589ad25b58adf8a54e97dbcded3f/.github/workflows/build.yml
build:
    stage: build
    script:
        - zypper install -y git-core checkpolicy policycoreutils-devel make m4 findutils
        - git clone --depth=1 https://github.com/containers/container-selinux.git /tmp/container-selinux
        - cp /tmp/container-selinux/container.* policy/modules/contrib
        - cp dist/targeted/modules.conf policy
        - make -j $(nproc) policy
        - make -j $(nproc) validate
        - make -j $(nproc) container.pp

rpmbuild:
    stage: rpmbuild
    script:
        - zypper ar -p 98 https://download.opensuse.org/repositories/security:/SELinux/openSUSE_Factory/ selinux
        - zypper --non-interactive --gpg-auto-import-keys dup --from selinux --allow-vendor-change
        # Install dependencies
        - zypper install -y wget rpm-build python-rpm-macros
        # Download the source RPM
        - cd ..
        - wget -r -nd -np -A "selinux-policy-*.src.rpm" https://download.opensuse.org/repositories/security:/SELinux/openSUSE_Factory/src/
        # Set the rpmbuild dir location
        - echo "%_topdir %(pwd)/rpmbuild" > ~/.rpmmacros
        # Unpack the source RPM and adjust the spec file
        - rpm -i selinux-policy-*.src.rpm
        - sed -i 's/%{name}-%{version}/%{name}/g' rpmbuild/SPECS/selinux-policy.spec
        # Replace the source tarball with the current git state
        - rm rpmbuild/SOURCES/selinux-policy-*.tar.xz
        - tar -cJf rpmbuild/SOURCES/selinux-policy.tar.xz selinux-policy
        # Install the build dependencies
        - zypper -n source-install -d selinux-policy-*.src.rpm
        # Build and move the RPMs into the artifacts dir
        - rpmbuild -bb rpmbuild/SPECS/selinux-policy.spec
        - mkdir selinux-policy/artifacts
        - mv rpmbuild/RPMS/noarch/* selinux-policy/artifacts
    artifacts:
        paths:
            - artifacts/

test:
    stage: test
    script:
        - set +e
        - zypper --non-interactive --quiet install qemu-img qemu-x86 rpm-devel wget
        - bash test/test.sh
    allow_failure:
        exit_codes:
            - 100
